services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: token-sync-service

    ports:
      - "8080:8080"

    environment:
      TZ: "UTC"

    volumes:
      - ./data:/data
      - ./cron:/cron
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

    restart: unless-stopped

volumes:
  seed-data:
  cron-output: